# Generated by Django 5.2.12 on 2026-04-07 01:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=130)),
                ('kind', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita'), ('both', 'Ambos')], default='expense', max_length=16, verbose_name='tipo')),
                ('color', models.CharField(default='#6C4CF1', max_length=7, verbose_name='cor (hex)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_system', models.BooleanField(default=False, help_text='Criada automaticamente; o usuário pode ocultar mas não excluir facilmente.', verbose_name='categoria do sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor total')),
                ('installment_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(120)], verbose_name='número de parcelas')),
                ('first_due_date', models.DateField(verbose_name='vencimento da 1ª parcela')),
                ('interval_months', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='intervalo entre parcelas (meses)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'plano de parcelamento',
                'verbose_name_plural': 'planos de parcelamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('due_soon', 'Vencimento próximo'), ('spending_spike', 'Gasto fora do padrão'), ('forecast_warning', 'Alerta de previsão'), ('weekly_summary', 'Resumo semanal'), ('monthly_summary', 'Resumo mensal'), ('insight', 'Insight automático'), ('other', 'Outro')], default='other', max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('body', models.TextField(verbose_name='mensagem')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='dia de vencimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('auto_create_transaction', models.BooleanField(default=True, help_text='Se verdadeiro, um job pode criar a transação do mês (ver comando de gestão).', verbose_name='gerar despesa automaticamente no mês')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'conta fixa (recorrente)',
                'verbose_name_plural': 'contas fixas (recorrentes)',
                'ordering': ['due_day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBillOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_paid', models.BooleanField(default=False, verbose_name='pago')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
            ],
            options={
                'verbose_name': 'ocorrência de conta fixa',
                'verbose_name_plural': 'ocorrências de contas fixas',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('transaction_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=16, verbose_name='tipo')),
                ('occurred_on', models.DateField(verbose_name='data')),
                ('is_recurring', models.BooleanField(default=False, help_text='Indica padrão recorrente além do plano de parcelas (ex.: assinatura).', verbose_name='recorrente')),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='número da parcela')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
                'ordering': ['-occurred_on', '-pk'],
            },
        ),
    ]
