# Generated by Django 5.2.12 on 2026-04-07 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recurringbill',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_recurring_bill_name_per_user'),
        ),
    ]
